/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function add(a: number, b: number): number
export function subtract(a: number, b: number): number
export function compare(a: number, b: number): number
export function decrement(value: number): number
export function increment(value: number): number
export function integerDivide(dividend: number, divisor: number): number
export function modulo(dividend: number, divisor: number): number
export function multiply(multiplicand: number, multiplier: number): number
export function power(base: number, exponent: number): number
export function toNumber(input: number): number
export function zero(): number
