[package]
name = "appw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-web-httpauth = "0.8.0"
actix-cors = "0.6.2"
derive_more = "0.99.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
