/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function minus(a: number, b: number): Promise<number>
export class AnimalWithDefaultConstructor {
  name: string
  kind: number
  constructor(name: string, kind: number)
}
export type JsQueryEngine = QueryEngine
export class QueryEngine {
  constructor()
  /** Class method */
  query(query: string): Promise<string>
  status(): number
}
